### ISSUE TITLE
Unknown database 'zotero_www'

### ISSUE THREAD

**Issue by JanVog** [SamuelHassine/zotero-prime#13]
I followed the very simple instructions of the readme (thanks for that) and also did what was recommended in issue #3 to make the server available for my whole local network.

Everything seemed to work fine so far, I can reach all Ports from everywhere in my network and the zotero client establishes a connection to the websocket on port 8081 without any errors.
But then it tries to connect to the API on Port 8080 (which I modified to listen on port 8084 instead, but that is not where the following error comes from) and the server returns a message with error code 500 (internal server error).

I did then look for error logs and found the apache 'error.log' in the zotero_app container.
This log file showed me the following error:

_WARNING: Exception: Unknown database 'zotero_www'_. What can I do now?

**Comment by hoehnp** [comment]
Have you called the init.sh script as mentioned in the README?
