### ISSUE TITLE
system requirements

### ISSUE THREAD

**Issue by hoehnp** [SamuelHassine/zotero-prime#7]
First of all thank you for your efforts and congratulations for succeeding with a successfully running installation. 

To ease deployment,  I wonder which linux system / version you used or recommend for deploying zotero-prime? Do you have some insights about the required hardware specifications?

Thanks a lot again.
Patrick

**Comment by mayeulk** [comment]
Hi,
It will depend a lot on the number of users and how often they interact with the server.
Being based on docker, the required OS does not matter much as soon as you can use a docker-compose.yml version: '3' (https://github.com/SamuelHassine/zotero-prime/blob/master/docker/docker-compose.yml )
This means you need at least Docker Engine release 1.13.0+
Source: https://docs.docker.com/compose/compose-file/

The OS which provide this for the Docker Enterprise edition are listed here:
https://success.docker.com/article/compatibility-matrix
(I could not find a link for CE - Community Edition)

The following are guesstimates:
- For small teams (max 3 or 5?), a single core CPU will probably do
- For larger teams (>5?), I'd suggest dual core and a SSD.
Mayeul

**Comment by mayeulk** [comment]
With respect to the linux version required, the linux package "[whohas](http://www.philippwesche.org/200811/whohas/intro.html)" might help you but the results are a bit cryptic.
The following is easier to use:
https://repology.org/project/docker-compose/versions

**Comment by mayeulk** [comment]
A few hints with respect to space requirement: (rough measures on Ubuntu 19.04)
git clone:  375 MB
sudo snap install docker : about 500 MB
build and run docker containers: about 2.5 GB
build zotero client for linux: > 500 MB (?)

The whole process took about 4GB of additional space for me (based on `df`, including some tools such as portainer...). Your mileage *will* vary; it's hard to measure disk usage when files go into various folders (and taking into account that the package manager of the host OS might download security updates for the OS in background). I suggest you do a test on a test machine, with `df -h` and `du` commands before and after installing zotero. You might save space by cross-compiling.

**Comment by hoehnp** [comment]
Sorry for the late response. @mayeulk. Thanks a lot for the suggestions, it is somehow inline with what I expected that small teams have pretty moderate requirements.
